name: release
on: push
jobs:
  build-project:
    name: Build Project
    strategy:
      matrix:
        os: [ubuntu, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Build
        run: ./build.sh --publish-folder ./publish-${{ matrix.os }}/
      - name: Publih build result
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: ./publish-${{ matrix.os }}/
  create-release:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: build-windows
      - name: Archive windows application
        uses: thedoctor0/zip-release@master
        with:
          filename: build-windows.zip
      - name: Download ubuntu artifact
        uses: actions/download-artifact@v3
        with:
          name: build-ubuntu
      - name: Archive ubuntu application
        uses: thedoctor0/zip-release@master
        with:
          filename: build-ubuntu.zip
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v.${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload windows asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build-windows.zip
          asset_name: build-windows.zip
          asset_content_type: application/zip
      - name: Upload ubuntu asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build-ubuntu.zip
          asset_name: build-ubuntu.zip
          asset_content_type: application/zip
