name: release
on: [workflow_dispatch]
jobs:
  build-project:
    name: Build Project
    strategy:
      matrix:
        os: [ubuntu, windows]
    runs-on: ${{ matrix.os }}-latest
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Set outputs
        id: build
        env:
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: false
        run: dotnet run --project build --publish-folder ./publish-${{ matrix.os }}/
      - name: Publih build result
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: ./publish-${{ matrix.os }}/
          if-no-files-found: error
  create-release:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-project
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v.${{ needs.build-project.outputs.version }}
          release_name: Release ${{ needs.build-project.outputs.version }}
          draft: false
          prerelease: false
  upload-artifacts:
    name: Upload Artifacts
    needs: create-release
    strategy:
      matrix:
        os: [windows, ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-${{ matrix.os }}
      - name: Archive application
        uses: thedoctor0/zip-release@master
        with:
          filename: build-${{ matrix.os }}.zip
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./build-${{ matrix.os }}.zip
          asset_name: build-${{ matrix.os }}.zip
          asset_content_type: application/zip
